blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question or share an idea
    url: https://github.com/mind2soft/audaciously/discussions
    about: Use GitHub Discussions for general questions, wild ideas, and "what if you tried…" threads.
