// features/nodes/instrument/instrument-node.ts
// InstrumentNode — piano/drum instrument with notes; buffer is synthesized.
// See: .opencode/context/refactor/01-terminology.md
//
// NOTE: The reactive synth render loop (watchEffect + synthWorker) is NOT here.
// It lives in composables/useInstrumentNode.ts (P4-02). This file is pure data.

import { nanoid } from "nanoid";
import type { ProjectNodeBase, ProjectNodeID } from "../node";
import type { AudioEffect } from "../../effects/types";
import type {
  InstrumentPitchKey,
  MusicInstrumentType,
  NoteDuration,
  OctaveRange,
} from "../../../lib/music/instruments";
import { PIANO_DEFAULT_OCTAVE_RANGE } from "../../../lib/music/instruments";

// ─── Re-exported types (originally from track/instrument/index.ts) ─────────────

export type PlacedNoteID = string;

export interface TimeSignature {
  /** Beats per measure (numerator). */
  beatsPerMeasure: number;
  /** Note value that receives one beat (denominator, e.g. 4 = quarter note). */
  beatUnit: number;
}

export const DEFAULT_TIME_SIGNATURE: TimeSignature = {
  beatsPerMeasure: 4,
  beatUnit: 4,
};

export interface PlacedNote {
  id: PlacedNoteID;
  /** Beat index from the start of the track (0-based, float allowed). */
  startBeat: number;
  /** Duration in beats. */
  durationBeats: number;
  /** Pitch key matching one of the instrument's pitches[].key values. */
  pitchKey: InstrumentPitchKey;
}

// ─── InstrumentNode interface ─────────────────────────────────────────────────

export interface InstrumentNode<
  InstrumentType extends MusicInstrumentType = MusicInstrumentType,
> extends ProjectNodeBase<"instrument"> {
  instrumentType: InstrumentType;
  bpm: number;
  timeSignature: TimeSignature;
  notes: PlacedNote[];
  selectedNoteType: NoteDuration;
  pitchScrollTop: number;
  octaveRange: OctaveRange;
  showWaveform: boolean;
  /**
   * The synthesized audio buffer with effects pre-baked, ready for playback.
   * Never persisted — regenerated by useInstrumentNode when notes/bpm/
   * timeSignature/effects change.  Null until the first render completes.
   */
  targetBuffer: AudioBuffer | null;
  /** Effects applied during playback of this node's buffer. */
  effects: AudioEffect[];
}

// ─── Factory ──────────────────────────────────────────────────────────────────

/** Create a new InstrumentNode with a unique id. */
export function createInstrumentNode<
  InstrumentType extends MusicInstrumentType,
>(
  name: string,
  instrumentType: InstrumentType,
  id?: ProjectNodeID,
): InstrumentNode<InstrumentType> {
  return {
    id: id ?? nanoid(),
    name,
    kind: "instrument",
    instrumentType,
    bpm: 120,
    timeSignature: { ...DEFAULT_TIME_SIGNATURE },
    notes: [],
    selectedNoteType: "quarter",
    pitchScrollTop: 0,
    octaveRange: { ...PIANO_DEFAULT_OCTAVE_RANGE },
    showWaveform: false,
    targetBuffer: null,
    effects: [],
  };
}
